export const config = {
    // DO NOT USE THESE CREDENTIALS ! THEY ARE HERE TO HELP IN THE LEARNING PROCESS.
    // ANY AND ALL DATA ON THAT DOMAIN IS SUBJECT TO CHANGE AND REMOVAL AT ANY TIME
    // THIS ACCOUNT IS ALSO ON THE FREE PLAN AND IS SUBJECT TO RESTRICTIONS !
    apiKey: "AIzaSyAl0JUNj6HLx99YIX1B83kNbWHJIbnu1cM",
    authDomain: "final-project-19b0c.firebaseapp.com",
    projectId: "final-project-19b0c"
  };